/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_frozeninferno_nexusbios_Andro7za */

#ifndef _Included_com_frozeninferno_nexusbios_Andro7za
#define _Included_com_frozeninferno_nexusbios_Andro7za
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_frozeninferno_nexusbios_Andro7za
 * Method:    a7za_print_usage
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_frozeninferno_nexusbios_Andro7za_a7za_1print_1usage
  (JNIEnv *, jobject);

JNIEXPORT jint JNICALL Java_com_frozeninferno_nexusbios_Andro7za_a7za_1unpack
  (JNIEnv *env, jobject obj, jstring outputPath, jstring inputFile);
#ifdef __cplusplus
}
#endif
#endif
